spring:
  application:
    name: spring-webflux-guide
  webflux:
    base-path: /api
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      post: 27017
      database: webflux
      username: admin
      password: admin

server:
  port: 9000
  http2:
    enabled: true

logging:
  level:
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG
